name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.2.0+cpu torchvision==0.17.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install pytest tqdm matplotlib pytest-html psutil
    
    - name: Train model
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) python train.py
    
    - name: Run tests
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/ -v --html=test-results.html --self-contained-html | tee -a $GITHUB_STEP_SUMMARY
    
    - name: Display Memory Usage
      run: |
        echo "## Memory Usage Summary" >> $GITHUB_STEP_SUMMARY
        python -c "
        import psutil
        process = psutil.Process()
        print(f'Memory Usage: {process.memory_info().rss / 1024 / 1024:.2f} MB', file=open('$GITHUB_STEP_SUMMARY', 'a'))
        "
    
    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/
        
    - name: Upload augmentation examples
      uses: actions/upload-artifact@v3
      with:
        name: augmentation-examples
        path: visualization/
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.html